service: sydney-bus-departures

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: ap-southeast-2
  environment:
    TFNSW_KEY: ${env:TFNSW_KEY}

functions:
  departures:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}

plugins:
    - serverless-offline
    - serverless-plugin-include-dependencies