service: sydney-bus-departures

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: ap-southeast-2
  environment:
    TFNSW_KEY: ${env:TFNSW_KEY}

functions:
  departures:
    handler: dist/lambda.handler
    events:
      - http: ANY {proxy+}

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - dist/**

plugins:
    - serverless-offline
    - serverless-plugin-include-dependencies