service: sydney-bus-departures

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  #stage: dev
  region: ap-southeast-2
# functions:
#   index:
#     handler: server-serverless.index
#     events:
#       http: any {proxy+}


functions:
  index:
    handler: handler.index
    events:
      - http: ANY {proxy+}


plugins:
    - serverless-offline